// Run this file in a terminal window with "node [relative file path]"
// The three seeder files should be run in order of userSeeds.js > toDoListSeeds.js > toDoListItemSeeds.js
// toDoListSeeder.js relies on the "_id" field values generated by userSeeder.js
// toDoListItemSeeder.js relies on the "_id" field values generated by toDoListSeeder.js
const mongoose = require('mongoose');
const hmsTime = require('../utilities/hmsTime.js');
const objectId = mongoose.Schema.Types.ObjectId;
const User = require('../models/user-model.js');
const ToDoList = require('../models/to-do-list-model');
const ToDoListItem = require('../models/to-do-list-item-model');

mongoose.connect('mongodb://localhost:27017/toDoListApp')
	.then(()=>{console.log(`${hmsTime()}: Mongo connection open.`)})
	.catch(error=>{console.log(`${hmsTime()}: Mongo error: ${error}`)});

const userSeeds = [
	{
		userName: 'Jerry Smith',
		userEmail: 'jerrysmith@example.com',
		userAccountCreationDate: '2023-04-04 09:19:05'
	},
	{
		userName: 'Larry Jones',
		userEmail: 'larryjones@example.com',
		userAccountCreationDate: '2023-03-03 07:14:05'
	},
	{
		userName: 'Harry Brown',
		userEmail: 'harrybrown@example.com',
		userAccountCreationDate: '2022-08-07 12:54:05'
	},
	{
		userName: 'Terry Jenkins',
		userEmail: 'terryjenkins@example.com',
		userAccountCreationDate: '2021-07-21 11:15:05'
	}
];

const seedUsers = async()=>{
	await User.deleteMany({})
		.then(res => {
			console.log(res)
	})
		.catch(e => {
			console.log(e)
	});
	await User.insertMany(userSeeds)
			.then(res => {
					console.log(res)
			})
			.catch(e => {
					console.log(e)
			});
}

seedUsers();
